services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: roadtrip_trips
    ports:
      - "5432:5432"
    volumes: #Volumes are Docker's way of creating permanent storage that survives container restarts.
      - postgres_data:/var/lib/postgresql/data #PostgreSQL stores its database files inside the container
        #postgres_data: A named volume managed by Docker
        #/var/lib/postgresql/data: The path inside the container
  trip-service:
    build: . #Tells Docker to look for a Dockerfile in the current directory
    ports:
      - "3000:3000" 
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: roadtrip_trips
    depends_on:
      - postgres
    volumes: # creates a "live connection" between your local code and the container:
      - ./src:/app/src #/app/src: Folder inside the container || ./src: Folder on your computer
      - ./test:/app/test
    command: npm run start:dev
# named volume create a storage area called postgres_data
volumes:
  postgres_data:  #managed entirely by Docker and optimized for performance.